{
 "title": "OpenWhisk Stats",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "kind", "label": "Language", "query": "label_values(kind) " },
   {
    "name": "action",
    "label": "Action",
    "query": "label_values(activations_total_counter{kind=~\"^$kind$\"}, action)"
   },
   { "name": "statusCode", "label": "Error Types", "query": "1,2,3" }
  ]
 },
 "panels": [
  {
   "title": "Invocations (by Language)",
   "type": "graph",
   "description": "Number of action invocations per second, filtered by kind (language)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(activations_total_counter{kind=~\"^$kind$\"}[1m]) * 15) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Invocations (by Action)",
   "type": "graph",
   "description": "Number of action invocations per second, filtered by action",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(activations_total_counter{action=~\"^$action$\"}[1m])*15) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Activation Duration (by Language & Action)",
   "type": "graph",
   "description": "The time duration for action execution, filtered by action and language",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(irate(activation_duration_counter{kind=~\"^$kind$\", action=~\"^$action$\"}[1m])*15) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Failed Invocations (by Error Types)",
   "type": "graph",
   "description": "Number of failed invocations/actions, filtered by error codes (error codes: 1,2,3)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(activations_total_counter{kind=~\"^$kind$\", action=~\"^$action$\", statusCode=~\"^$statusCode$\"}[1m])*15) by (statusCode)",
     "legendFormat": "{{statusCode}}"
    }
   ]
  }
 ]
}
{
 "title": "Cluster Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster CPU usage (5 min avg)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$node$\"}[5m])) / sum(machine_cpu_cores{kubernetes_io_hostname=~\"^$node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$node$\"}) / sum(machine_memory_bytes{kubernetes_io_hostname=~\"^$node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$node$\"}) / sum(container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$node$\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{kubernetes_io_hostname=~\"^$node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 8 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 8 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(machine_memory_bytes{kubernetes_io_hostname=~\"^$node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 8 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$node$\"})"
    }
   ]
  },
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Cluster CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$node$\"}[5m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$node$\"}) * 100",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$node$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$node$\"}) * 100",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Cluster Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$node$\"}) * 100",
     "legendFormat": "Received"
    }
   ]
  },
  { "title": "Network Pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Cluster Network I/O Pressure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$node$\"}[5m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$node$\"}[5m]))",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}
{
 "title": "System Services Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Services CPU Usage (5 min avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(irate(container_cpu_usage_seconds_total{id=~\"^/system\\\\.slice/.+\\\\.service$\",kubernetes_io_hostname=~\"^$node$\"}[5m]), \"systemd_service_name\", \"$1\", \"id\", \"^/system\\\\.slice/(.+)\\\\.service$\")) by (systemd_service_name)",
     "legendFormat": "{{ systemd_service_name }}"
    }
   ]
  },
  {
   "title": "System Services Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (label_replace (container_memory_working_set_bytes{id=~\"^/system\\\\.slice/.+\\\\.service$\",kubernetes_io_hostname=~\"^$node$\"}, \"systemd_service_name\", \"$1\", \"id\", \"^/system\\\\.slice/(.+)\\\\.service$\")) by (systemd_service_name)",
     "legendFormat": "{{ systemd_service_name }}"
    }
   ]
  }
 ]
}
{
 "title": "Pod Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod CPU Usage (5 min avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$node$\"}[5m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$node$\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pod Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$node$\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  { "title": "Network Pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Pod Network I/O Pressure (Receive)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$node$\"}[5m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pod Network I/O Pressure (Transmit)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$node$\"}[5m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  }
 ]
}
{
 "title": "OpenWhisk Health Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "invoker_pod", "label": "Invoker Pod", "query": "label_values(pod)" },
   { "name": "controller_pod", "label": "Controller Pods", "query": "label_values(pod)" }
  ]
 },
 "panels": [
  { "title": "Controller Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$controller_pod Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "repeat": "controller_pod",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{condition=\"true\", pod=~\"^$controller_pod$\"}) by (pod) * 5 + sum(kube_pod_status_ready{condition=\"unknown\", pod=~\"^$controller_pod$\"}) by (pod) * 3 + sum(kube_pod_status_ready{condition=\"false\", pod=~\"^$controller_pod$\"}) by (pod)"
    }
   ]
  },
  { "title": "Invoker Pool Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "$invoker_pod Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 },
   "repeat": "invoker_pod",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{condition=\"true\", pod=~\"^$invoker_pod$\"}) by (pod) * 5 + sum(kube_pod_status_ready{condition=\"unknown\", pod=~\"^$invoker_pod$\"}) by (pod) * 3 + sum(kube_pod_status_ready{condition=\"false\", pod=~\"^$invoker_pod$\"}) by (pod)"
    }
   ]
  },
  { "title": "Other Component Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CouchDB Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{condition=\"true\", pod=~\"^couchdb.*$\"}) by (pod) * 5 + sum(kube_pod_status_ready{condition=\"unknown\", pod=~\"^couchdb.*$\"}) by (pod) * 3 + sum(kube_pod_status_ready{condition=\"false\", pod=~\"^couchdb.*$\"}) by (pod)"
    }
   ]
  },
  {
   "title": "NginX Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{condition=\"true\", pod=~\"^nginx.*$\"}) by (pod) * 5 + sum(kube_pod_status_ready{condition=\"unknown\", pod=~\"^nginx.*$\"}) by (pod) * 3 + sum(kube_pod_status_ready{condition=\"false\", pod=~\"^nginx.*$\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Kafka Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{condition=\"true\", pod=~\"^kafka.*$\"}) by (pod) * 5 + sum(kube_pod_status_ready{condition=\"unknown\", pod=~\"^kafka.*$\"}) by (pod) * 3 + sum(kube_pod_status_ready{condition=\"false\", pod=~\"^kafka.*$\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Zookeeper Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{condition=\"true\", pod=~\"^zookeeper.*$\"}) by (pod) * 5 + sum(kube_pod_status_ready{condition=\"unknown\", pod=~\"^zookeeper.*$\"}) by (pod) * 3 + sum(kube_pod_status_ready{condition=\"false\", pod=~\"^zookeeper.*$\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Controller Restarts (Last 5 min)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }
  },
  {
   "title": "$controller_pod Restarts (Last 5 min)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 },
   "repeat": "controller_pod",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~\"^$controller_pod$\"}[5m])) by (pod)"
    }
   ]
  },
  {
   "title": "Invoker Pool Restarts (Last 5 min)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "$invoker_pod Restarts (Last 5 min)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "repeat": "invoker_pod",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~\"^$invoker_pod$\"}[5m])) by (pod)"
    }
   ]
  },
  {
   "title": "Other Component Restarts (Last 5 min)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "CouchDB Restarts (Last 5 min)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~\"^couchdb.*$\"}[5m])) by (pod)"
    }
   ]
  },
  {
   "title": "NginX Restarts (Last 5 min)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~\"^nginx.*$\"}[5m])) by (pod)"
    }
   ]
  },
  {
   "title": "Kafka Restarts (Last 5 min)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~\"^kafka.*$\"}[5m])) by (pod)"
    }
   ]
  },
  {
   "title": "Zookeeper Restarts (Last 5 min)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~\"^zookeeper.*$\"}[5m])) by (pod)"
    }
   ]
  }
 ]
}