apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus-statsd-exporter.fullname" . }}
  labels:
    app: {{ template "prometheus-statsd-exporter.name" . }}
    chart: {{ template "prometheus-statsd-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.statsdPort }}
      targetPort: {{ .Values.service.statsdTargetPort }}
      protocol: UDP
      name: statsd
    - port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.service.metricsTargetPort }}
      protocol: TCP
      name: metrics
  selector:
    app: {{ template "prometheus-statsd-exporter.name" . }}
    release: {{ .Release.Name }}
